inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  CacheRootDirectory: ./tmp/cache
  Exclude:
    - 'config/deploy.rb'
    - 'config/deploy/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 88

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
